// <auto-generated />
using System;
using ArtStep.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtStep.Migrations
{
    [DbContext(typeof(ArtStepDbContext))]
    partial class ArtStepDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtStep.Data.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("isStatus")
                        .HasColumnType("smallint");

                    b.HasKey("AccountId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ArtStep.Data.Cart", b =>
                {
                    b.Property<string>("CartId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ArtStep.Data.CartDetail", b =>
                {
                    b.Property<string>("CartDetailID")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CartId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("QuantityBuy")
                        .HasColumnType("int");

                    b.Property<string>("ShoeCustomId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CartDetailID");

                    b.HasIndex("CartId");

                    b.HasIndex("ShoeCustomId");

                    b.ToTable("CartsDetail");
                });

            modelBuilder.Entity("ArtStep.Data.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ArtStep.Data.Feedback", b =>
                {
                    b.Property<string>("FeedbackId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DesignerReceiveFeedbackId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FeedbackDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FeedbackStars")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserSendFeedbackId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("FeedbackId");

                    b.HasIndex("DesignerReceiveFeedbackId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserSendFeedbackId");

                    b.ToTable("feedback", (string)null);
                });

            modelBuilder.Entity("ArtStep.Data.Message", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("MessageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("MessageType")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceivedId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("SendAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SenderId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MessageId");

                    b.HasIndex("ReceivedId");

                    b.HasIndex("SenderId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("ArtStep.Data.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("VNPayPaymentId")
                        .HasColumnType("bigint");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("ArtStep.Data.OrderDetail", b =>
                {
                    b.Property<string>("OrderDetailId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("CostaShoe")
                        .HasColumnType("float");

                    b.Property<string>("OrderId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("QuantityBuy")
                        .HasColumnType("int");

                    b.Property<string>("ShoeCustomId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ShoeCustomId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("ArtStep.Data.ShoeCustom", b =>
                {
                    b.Property<string>("ShoeId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DesignerUserId")
                        .HasColumnType("nvarchar(255)");

                    b.Property<short?>("IsHidden")
                        .HasColumnType("smallint");

                    b.Property<double?>("PriceAShoe")
                        .HasColumnType("float");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ShoeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShoeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoeId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DesignerUserId");

                    b.ToTable("ShoeCustom");
                });

            modelBuilder.Entity("ArtStep.Data.ShoeImage", b =>
                {
                    b.Property<string>("ImageId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShoeCustomId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ImageId");

                    b.HasIndex("ShoeCustomId");

                    b.ToTable("ShoeImages");
                });

            modelBuilder.Entity("ArtStep.Data.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageProfile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("isActive")
                        .HasColumnType("smallint");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ArtStep.Data.Wallet", b =>
                {
                    b.Property<string>("WalletId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<short>("IsActive")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("ArtStep.Data.WalletTransaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<double>("BalanceAfter")
                        .HasColumnType("float");

                    b.Property<double>("BalanceBefore")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WalletId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TransactionId");

                    b.HasIndex("OrderId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("ArtStep.Data.Account", b =>
                {
                    b.HasOne("ArtStep.Data.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("ArtStep.Data.Account", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArtStep.Data.Cart", b =>
                {
                    b.HasOne("ArtStep.Data.User", "Users")
                        .WithOne("Cart")
                        .HasForeignKey("ArtStep.Data.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ArtStep.Data.CartDetail", b =>
                {
                    b.HasOne("ArtStep.Data.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("CartId");

                    b.HasOne("ArtStep.Data.ShoeCustom", "ShoeCustom")
                        .WithMany("CartDetails")
                        .HasForeignKey("ShoeCustomId");

                    b.Navigation("Cart");

                    b.Navigation("ShoeCustom");
                });

            modelBuilder.Entity("ArtStep.Data.Feedback", b =>
                {
                    b.HasOne("ArtStep.Data.User", "DesignersReceived")
                        .WithMany("ReceivedFeedbacks")
                        .HasForeignKey("DesignerReceiveFeedbackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArtStep.Data.Order", "Order")
                        .WithMany("Feedbacks")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArtStep.Data.User", "UserSend")
                        .WithMany("SentFeedbacks")
                        .HasForeignKey("UserSendFeedbackId");

                    b.Navigation("DesignersReceived");

                    b.Navigation("Order");

                    b.Navigation("UserSend");
                });

            modelBuilder.Entity("ArtStep.Data.Message", b =>
                {
                    b.HasOne("ArtStep.Data.User", "UserReceived")
                        .WithMany()
                        .HasForeignKey("ReceivedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArtStep.Data.User", "UserSend")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UserReceived");

                    b.Navigation("UserSend");
                });

            modelBuilder.Entity("ArtStep.Data.Order", b =>
                {
                    b.HasOne("ArtStep.Data.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArtStep.Data.OrderDetail", b =>
                {
                    b.HasOne("ArtStep.Data.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId");

                    b.HasOne("ArtStep.Data.ShoeCustom", "ShoeCustom")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ShoeCustomId");

                    b.Navigation("Order");

                    b.Navigation("ShoeCustom");
                });

            modelBuilder.Entity("ArtStep.Data.ShoeCustom", b =>
                {
                    b.HasOne("ArtStep.Data.Category", "Category")
                        .WithMany("ShoeCustoms")
                        .HasForeignKey("CategoryId");

                    b.HasOne("ArtStep.Data.User", "Designer")
                        .WithMany("ShoeCustoms")
                        .HasForeignKey("DesignerUserId");

                    b.Navigation("Category");

                    b.Navigation("Designer");
                });

            modelBuilder.Entity("ArtStep.Data.ShoeImage", b =>
                {
                    b.HasOne("ArtStep.Data.ShoeCustom", "ShoeCustom")
                        .WithMany("Images")
                        .HasForeignKey("ShoeCustomId");

                    b.Navigation("ShoeCustom");
                });

            modelBuilder.Entity("ArtStep.Data.Wallet", b =>
                {
                    b.HasOne("ArtStep.Data.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("ArtStep.Data.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArtStep.Data.WalletTransaction", b =>
                {
                    b.HasOne("ArtStep.Data.Order", "Order")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArtStep.Data.Wallet", "Wallet")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("ArtStep.Data.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("ArtStep.Data.Category", b =>
                {
                    b.Navigation("ShoeCustoms");
                });

            modelBuilder.Entity("ArtStep.Data.Order", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("OrderDetails");

                    b.Navigation("WalletTransactions");
                });

            modelBuilder.Entity("ArtStep.Data.ShoeCustom", b =>
                {
                    b.Navigation("CartDetails");

                    b.Navigation("Images");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ArtStep.Data.User", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("ReceivedFeedbacks");

                    b.Navigation("SentFeedbacks");

                    b.Navigation("ShoeCustoms");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("ArtStep.Data.Wallet", b =>
                {
                    b.Navigation("WalletTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
