version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    ports:
      - "5000:80"
    networks:
      - artstep-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: final-frontend
    ports:
      - "7216:7216"
    networks:
      - artstep-network

networks:
  artstep-network:
    driver: bridge
